version: "3.1"

services:
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: godwin
      POSTGRES_DB: jwt_security
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"